name: Code Review Reminder

on:
  schedule:
    - cron: '0 0 * * *'  # Set the schedule based on your preference, e.g., every day at midnight

jobs:
  code_review_reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: pip install requests
    
    - name: Run Code Review Reminder
      run: python .github/scripts/code_review_reminder.py ${{ secrets.GITHUB_TOKEN }}
